// src/utils/useTranslate.js
import { useLanguage } from "../context/LanguageContext";

const dictionary = {
  en: {
    "Edit Profile": "Edit Profile",
    "Share": "Share",
    "Settings": "Settings",
    "Followers": "Followers",
    "Following": "Following",
    "Films": "Films",
    "Profile": "Profile",
    "Reviews": "Reviews",
    "Watchlist": "Watchlist",
    "Lists": "Lists",
    "Follow": "Follow",
    "Following (btn)": "Following", 
    "Log Out": "Log Out",
    "Delete Account": "Delete Account",
    "Change Language": "Change Language",
    "Remove Follower": "Remove Follower",
    "🔗 Profile link copied!": "🔗 Profile link copied!",
    "Couldn’t copy link": "Couldn’t copy link",
    "Favorite Movies": "Favorite Movies",
"No favorite movies yet.": "No favorite movies yet.",
"Recent Activities": "Recent Activities",
"No recent logs yet.": "No recent logs yet.",
"More →": "More →",
"Connections": "Connections",
"Hide": "Hide",
"Show": "Show",
"Most Recent": "Most Recent",
    "Most Likes": "Most Likes",
    "reply": "reply",
    "replies": "replies",
    "Account": "Account",
    "App Info": "App Info",
    "Contact Us": "Contact Us",
    "Built with ❤️ in Saudi Arabia": "Built with ❤️ in Saudi Arabia",
    "All rights reserved.": "All rights reserved.",

    "Loading your Scenes...": "Loading your Scenes...",
    "Recently Added": "Recently Added",
    "Release Date": "Release Date",
    "Rating": "Rating",
    "Runtime": "Runtime",
    "All Genres": "All Genres",
    "Action": "Action",
    "Comedy": "Comedy",
    "Drama": "Drama",
    "Horror": "Horror",
    "Romance": "Romance",
    "Animation": "Animation",
    "Music": "Music",
    "Crime": "Crime",
    "Thriller": "Thriller",
    "This movie has no valid TMDB ID.": "This movie has no valid TMDB ID.",
    "This watchlist is empty.": "This watchlist is empty.",

    "My lists": "My lists",
    "Saved": "Saved",
    "Popular": "Popular",
    "Friends": "Friends",
    "Add List": "Add List",
    "unknown": "unknown",

    "Favorites": "Favorites",
    "Descending": "Descending",
    "Ascending": "Ascending",
    "You haven’t marked any favorite films yet.": "You haven’t marked any favorite films yet.",
    "No films found for this filter.": "No films found for this filter.",
    "Poster": "Poster",

    "No changes to save.": "No changes to save.",
    "Profile updated!": "Profile updated!",
    "Failed to update profile.": "Failed to update profile.",
    "Avatar uploaded!": "Avatar uploaded!",
    "Avatar upload failed.": "Avatar upload failed.",
    "Back": "Back",
    "Save": "Save",
    "Backdrop": "Backdrop",
    "Avatar": "Avatar",
    "Change Photo": "Change Photo",
    "Change backdrop": "Change backdrop",
    "Bio": "Bio",
    "Write a short bio (max 180 chars)": "Write a short bio (max 180 chars)",
    "Favorite Films": "Favorite Films",
    "No favorite movies yet.": "No favorite movies yet.",
    "Add Movie": "Add Movie",
    "Connections": "Connections",
    "Add your social links (X, YouTube, etc.)": "Add your social links (X, YouTube, etc.)",
    "Add / Edit Connections": "Add / Edit Connections",
    "Enter your {{platform}} link or username": "Enter your {{platform}} link or username",
    "Transfer Data from Letterboxd": "Transfer Data from Letterboxd",

    "Import complete.": "Import complete.",
    "Welcome to Scene!": "Welcome to Scene!",
    "Cleared last import.": "Cleared last import.",
    "How to import": "How to import",
    "Transfer Data from Letterboxd": "Transfer Data from Letterboxd",
    "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).": "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).",
    "Uploading files...": "Uploading files don't close Scene...",
    "Upload All Files": "Upload All Files",
    "Continue to Profile": "Continue to Profile",
    "Undo Last Import": "Undo Last Import",
    "How to Import from Letterboxd": "How to Import from Letterboxd",
    "Go to your Letterboxd account on the website (not the app).": "Go to your Letterboxd account on the website (not the app).",
    "Go to Settings → Export your data.": "Go to Settings → Export your data.",
    "Come back to Scene.": "Come back to Scene.",
    "Upload them here in the correct fields.": "Upload them here in the correct fields.",
    "Click Save — we'll handle the rest! 🚀": "Click Save — we'll handle the rest! 🚀",
    "Close": "Close",
    "Back": "Back",
    "❌ Import failed for {{type}}": "❌ Import failed for {{type}}",

    "Add Movie": "Add Movie",
    "Back": "Back",
    "Search movies...": "Search movies...",
    "Loading...": "Loading...",
    "No results found.": "No results found.",
    "Already added": "Already added",
    "Added": "Added",

    "Followers": "Followers",
    "Following": "Following",
    "User": "User",
    "Back": "Back",
    "No users found.": "No users found.",
    "Follow": "Follow",
    "Unfollow": "Unfollow",
    "{{name}}’s {{tab}}": "{{name}}’s {{tab}}",

    "Link copied with preview!": "Link copied (Previews are cooming soon!) ",
    "🎨 Change Backdrop": "🎨 Change Backdrop",
    "✏️ Edit Review/Log": "✏️ Edit Review/Log",
    "🗑️ Delete Review/Log": "🗑️ Delete Review/Log",
    "📤 Share to Friends": "📤 Share to Friends",
    "💾 Save Photo": "💾 Save Photo",
    "🔗 Copy Link": "🔗 Copy Link",
    "Go to Movie": "Go to Movie",
    "Backdrop": "Backdrop",
    "Avatar": "Avatar",
    "Just now": "Just now",
    "{{n}}m ago": "{{n}}m ago",
    "{{n}}h ago": "{{n}}h ago",
    "{{n}}d ago": "{{n}}d ago",
    "Rewatch count": "Rewatch count",
    "Attached image": "Attached image",
    "GIF": "GIF",
    "Like": "Like",
    "Reply": "Reply",
    "Back": "Back",

    "Delete this review?": "Delete this review?",
    "Review deleted!": "Review deleted!",
    "Failed to delete review.": "Failed to delete review.",
    "Failed to load review.": "Failed to load review.",
    "You must be logged in to like.": "You must be logged in to like.",
    "Failed to like.": "Failed to like.",
    "Failed to like reply.": "Failed to like reply.",
    "Comments": "Comments",
    "No comments yet.": "No comments yet.",
    "Avatar": "Avatar",
    "Image": "Image",
    "Mystery": "Mystery",
    "Adventure": "Adventure",
    "Family": "Family",

    "More reviews": "More reviews",
    "…read more": "Read more...",

    "No comments yet. Be the first to reply!": "No comments yet. Be the first to reply!",
    "Options": "Options",
    "Delete": "Delete",
    "Reply sent": "Reply sent",
    "Failed to send reply": "Failed to send reply",
    "Delete this reply?": "Delete this reply?",
    "Reply deleted": "Reply deleted",
    "Failed to delete reply": "Failed to delete reply",
    "Preview": "Preview",
    "Remove attachment": "Remove attachment",
    "Add image": "Add image",
    "Add GIF": "Add GIF",
    "Write a comment...": "Write a comment...",
    "Send": "Send",


    "List title": "List title",
    "Description (optional)": "Description (optional)",
    "Upload a cover image (optional)": "Upload a cover image (optional)",
    "Cover": "Cover",
    "Remove": "Remove",
    "Private": "Private",
    "Ranked": "Ranked",
    "Movies in this list:": "Movies in this list:",
    "No movies added yet.": "No movies added yet.",
    "Add Movie": "Add Movie",
    "List created!": "List created!",
    "Failed to create list.": "Failed to create list.",
    "Upload failed.": "Upload failed.",
    "Cover uploaded!": "Cover uploaded!",

    "Failed to load list.": "Failed to load list.",
    "List updated!": "List updated!",
    "Failed to update list.": "Failed to update list.",
    "Are you sure you want to delete this list?": "Are you sure you want to delete this list?",
    "List deleted.": "List deleted.",

    "You must be logged in.": "You must be logged in.",
    "Something went wrong.": "Something went wrong.",
    "List saved!": "List saved!",
    "List unsaved!": "List unsaved!",
    "Are you sure you want to delete this list?": "Are you sure you want to delete this list?",
    "List deleted!": "List deleted!",
    "Failed to delete list.": "Failed to delete list.",
    "Loading...": "Loading...",
    "More options": "More options",
    "ask_anything": "Ask Anything About Movies...",
    "Edit List": "Edit List",
    "Share to Friends": "Share to Friends",
    "Delete List": "Delete List",
    "Save List": "Save List",
    "Ranked Movies": "Ranked Movies",
    "Movies": "Movies",
    "Untitled": "Untitled",

    "Notifications": "Notifications",
    "You're all caught up. No notifications yet!": "You're all caught up. No notifications yet!",
    "Failed to load notifications": "Failed to load notifications",
    "🔔 New notification": "🔔 New notification",
    "Something went wrong": "Something went wrong",
    "just followed you": "just followed you",
    "liked your review": "liked your review",
    "liked your comment": "liked your comment",
    "replied to your comment": "replied to your comment",
    "liked your list!": "liked your list!",
    "suggested you to check out this list!": "suggested you to check out this list!",
    "suggested you to check out this film!": "suggested you to check out this film!",
    "suggested you to check out this review!": "suggested you to check out this review!",
    "shared a movie with you!": "shared a movie with you!",
    "sent you something!": "sent you something!",
    "View Movie": "View Movie",
    "View List": "View List",
    "View Review": "View Review",

    "Search": "Search",
    "Recent Searches": "Recent Searches",
    "Clear": "Clear",
    "No results found": "No results found",
    "Movies": "Movies",
    "Users": "Users",
    "Lists": "Lists",
    "Actors": "Actors",
    "Directors": "Directors",
    "Trending Searches": "Trending Searches",
    "Search results": "Search results",
    "More →": "More →",

    "Loading your Scenes...": "Loading your Scenes...",
    "Welcome back, {name} 🎬": "Welcome back, {name} 🎬",
    "Profile": "Profile",
    "New Day. New Amazing Film. It’s a Scene Thing. 🎥": "New Day. New Amazing Film. It’s a Scene Thing. 🎥",
    "Recent Activities": "Recent Activities",
    "No recent logs yet.": "No recent logs yet.",
    "Trending Movies": "Trending Movies",
 
    "No trending movies right now.": "No trending movies right now.",

    "Trending Movies This Week 🔥": "Trending Movies This Week 🔥",
    "No trending movies available.": "No trending movies available.",

    "Ask Anything about Movies...": "Ask Anything about Movies...",
    "SceneBot is typing...": "SceneBot is typing...",
    "Send": "Send",
    "Surprise me!": "Surprise me!",
    "Something went wrong": "Something went wrong",

    "Loading...": "Loading...",
    "Profile link copied!": "Profile link copied!",
    "Remove this follower?": "Remove this follower?",
    "Removed follower!": "Removed follower!",
    "Failed to remove follower.": "Failed to remove follower.",

    "loading_movie": "Loading movie...",
    "overview": "Overview",
    "director": "Director",
    "no_director_found": "No director found",
    "starring": "Starring",
    "watched_by_friends": "Watched by Friends",
    "no_friends_logged": "No friends have logged this film yet.",
    "more": "More →",
    "popular_reviews": "Popular Reviews",
    "no_reviews": "No reviews yet.",
    "reply": "Reply",
    "read_more": "Read more",
    "time.just_now": "Just now",
    "time.minutes_ago": "{{min}}min ago",
    "time.hours_ago": "{{hr}}h ago",
    "time.days_ago": "{{day}}d ago",
    "alt.backdrop": "Backdrop",
    "no_trailer": "No trailer available",
    "scenebot_autoask": "What do you think about \"{{title}}\"?", 

    "alt.poster": "Poster",
    "minutes": "min",
    "log": "Log",
    "trailer": "Trailer",
    "ask_scenebot": "Ask SceneBot", 

 
          "not_logged_in": "Not logged in",
          "invalid_movie_id": "Invalid movie id",
          "watchlist_update_failed": "Failed to update watchlist",
          "favorites_update_failed": "Failed to update favorites",
          "delete_log_failed": "Failed to delete log",
      
    
          "added": "Added to Watchlist",
          "removed": "Removed from Watchlist",
    
  
          "added": "Added to Favorites",
          "removed": "Removed from Favorites",
      
 

  

          "deleted_success": "Log deleted successfully!",
     

     
  
              "change_poster": "Change Poster",
              "remove_from_watchlist": "Remove From Watchlist",
              "add_to_watchlist": "Add to Watchlist",
              "remove_from_favorites": "Remove From Favorites",
              "add_to_favorites": "Add to Favorites",
              "add_to_list": "Add to List",
              "share_to_friend": "Share to a Friend",
              "delete_log": "Delete Log",
           
    
          


          "back": "Back",
          "open_menu": "Open menu",

          "Full Cast": "Full Cast",
          "Similar Films": "Similar Films",
          "Where to Watch": "Where to Watch",

          "poster.choose_new": "Choose a New Poster",
          "poster.confirm": "✅ Confirm",
          "poster.saving": "Saving...",
          "poster.close": "Close",
          "poster.approved_only": "Only the approved poster can be used for this film.",

          "no_rating_yet": "No rating yet",
          "marked_as_favorite": "Marked as Favorite",
          "mark_as_favorite": "Mark as Favorite",
          "mark_as_rewatch": "Mark as Rewatch",
          "write_your_thoughts": "Write your thoughts...",
          "update": "Update",
          "log": "Log",
          "log_updated": "✅ Log updated!",
          "log_deleted": "Log Deleted 🗑️",
          "log_submitted": "🎬 Log submitted!",
          "log_failed": "Failed to submit log.",

          "confirm_delete_log_title": "Delete Log?",
          "confirm_delete_log_message": "Are you sure you want to delete this log? This action cannot be undone.",
          "cancel": "Cancel",
          "delete": "Delete",

          "watchlist.added": "Added to Watchlist ✅",
          "watchlist.removed": "Removed from Watchlist ❌",
          "favorites.added": "Added to Favorites ❤️",
          "favorites.removed": "Removed from Favorites ❌",

          "not_logged_in": "Not logged in",
          "untitled_log": "Untitled Log",
          "untitled_list": "Untitled List",
          "select_at_least_one": "Select at least one friend.",
          "suggested_success": "✅ Suggested to {{count}} friend(s)!",
          "failed_to_send": "Failed to send suggestions.",
          "loading": "Loading...",
          "invalid_resource": "Invalid resource",
          "something_wrong": "Something went wrong.",
          "go_back": "Go Back",
          "share_to_friends": "Share to Friends",
          "send": "Send",
          "no_mutual_followers": "You have no mutual followers yet.",

          "lists.select_add": "Select a list to add this film",
          "lists.loading": "Loading your lists...",
          "lists.none_yet": "You haven’t made any lists yet.",
          "lists.failed_load": "❌ Failed to load your lists",
          "lists.added_success": "✅ Added to list!",
          "lists.added_fail": "❌ Failed to add movie.",

          "watched_by": "Watched by",
          "friends": "Friends",
          "all": "All",
          "no_friends_logged": "No friends have logged this film yet.",
          "no_one_logged": "No one has logged this film yet.",

          "just_now": "Just now",
          "minutes_ago": "{min}min ago",
          "hours_ago": "{hr}h ago",
          "days_ago": "{day}d ago",

          "friends_reviews": "Friends Reviews",
          "all_reviews": "All Reviews",

          "write_reply": "Write a reply...",
          "reply_sent": "Reply sent 🎉",
          "reply_failed": "Failed to send reply ❌",
          "Loading review…":"Loading review…",
          "loading": "Loading...",
          "check_imdb": "This person may have awards – check IMDb for more",
          "read_more": "Read more",
          "show_less": "Show less",
          "all_films": "All Films",
          "all_directed_films": "All Directed Films",

          "awards.imdb_fallback": "🏆 {{name}} may have awards – check IMDb for more",

          "Loading...": "Loading...",
    "I’ve rated": "I’ve rated",
    "on": "on",
    "Saved! Check your device's Downloads folder.": "Saved! Check your device's Downloads folder.",

    "Change Backdrop": "Change Backdrop",
    "Search for a movie": "Search for a movie",
    "Loading backdrops...": "Loading backdrops...",
    "Done": "Done",

    "loading_actor": "Loading actor…",
    "loading_director": "Loading director…",

      "select_a_list": "Select a List",
  "no_lists_yet": "You don’t have any lists yet.",

  "not_logged_in": "You need to log in first",
  "invalid_movie_id": "Invalid movie ID",
  "watchlist_update_failed": "Failed to update watchlist",
  "favorites_update_failed": "Failed to update favorites",
  "delete_log_failed": "Failed to delete log",
  "failed_load_lists": "Failed to load your lists",
  "missing_movie": "Movie data is missing",
  "failed_add_to_list": "Failed to add movie to list",


  "added": "Added to your Watchlist",
  "removed": "Removed from your Watchlist",

  "added": "Added to Favorites",
  "removed": "Removed from Favorites",


  "deleted_success": "Log deleted successfully",


  "title": "Are you sure?",

  "added_to": "Added to",
  "already_in_list": "This movie is already in the list",
  "select_a_list": "Select a List",
  "no_lists_yet": "You don’t have any lists yet.",
  "like": "like",
  "likes": "likes",
  "logout": "Logout",
  "Films": "Films",
  "Loading...": "Loading...",
    
  "Search for a movie": "Search for a movie",
  "Privacy Policy":"Privacy Policy",

  "Join Scene": "Join Scene",
"Create your account to log your films": "Create your account to log your films",
"Upload Avatar": "Upload Avatar",
"Username": "Username",
"Email": "Email",
"Password": "Password",
"Choose Language": "Choose Language",
"Selected": "Selected",
"Sign Up": "Sign Up",
"Already have an account?": "Already have an account?",
"Log in": "Log in",

"Please upload an avatar.": "Please upload an avatar.",
"Invalid username format.": "Invalid username format.",
"Username already taken.": "Username already taken.",
"Invalid email.": "Invalid email.",
"Email already in use.": "Email already in use.",
"Password too short.": "Password too short.",
"Account created!": "Account created!",
"Signup failed. Try again.": "Signup failed. Try again.",
"Error": "Error",
"English selected": "English selected",
"Arabic selected": "Arabic selected",

"Loading cinematographer...": "Loading cinematographer...",
"Cinematographer not found.": "Cinematographer not found.",
"Go Back": "Go Back",
"Unknown": "Unknown",
"Untitled": "Untitled",
"User": "User",

"Cinematographer": "Cinematographer",
"Camera Department": "Camera Department",
"Award data coming soon": "Award data coming soon",
"cinematography credits on Scene": "cinematography credits on Scene",

"Awards": "Awards",
"Biography": "Biography",
"No biography yet.": "No biography yet.",

"Career Progress": "Career Progress",
"You": "You",
"watched": "watched",
"Friends": "Friends",
"friends": "friends",

"Cinematography Credits": "Cinematography Credits",
"No cinematography credits found.": "No cinematography credits found.",

"Friends Career %": "Friends Career %",
"No mutual friends have watched this cinematographer yet.": "No mutual friends have watched this cinematographer yet.",

"Your watched credits": "Your watched credits",
"of credits by": "of credits by",
"No watched cinematography credits yet.": "No watched cinematography credits yet.",
"Logged": "Logged",
  "No cast available.": "No cast available.",
"Cinematography": "Cinematography",
"Unknown": "Unknown",
"Full Cast": "Full Cast",
"Show less": "Show less",
"Show more": "Show more",
"Loading actor...": "Loading actor...",
"Actor not found.": "Actor not found.",
"Go Back": "Go Back",
"Unknown": "Unknown",
"Untitled": "Untitled",
"User": "User",

"Actor": "Actor",
"Award data coming soon": "Award data coming soon",
"films on Scene": "films on Scene",

"Awards": "Awards",
"Biography": "Biography",
"No biography yet.": "No biography yet.",

"Career Progress": "Career Progress",
"You": "You",
"watched": "watched",
"Friends": "Friends",
"friends": "friends",

"All Films": "All Films",
"No films found.": "No films found.",

"Friends Career %": "Friends Career %",
"No mutual friends have watched this actor yet.": "No mutual friends have watched this actor yet.",

"Your watched films": "Your watched films",
"of career by": "of career by",
"No watched films from this actor yet.": "No watched films from this actor yet.",
"Logged": "Logged",

"Saudi talent message Arabic": "نحتفي ونفخر بإرث السعودية السينمائي المتنامي.\nكمؤسس للمنصة، أنشأت Scene على أمل أن نسهم في نمو السينما السعودية،\nوأن نلهم الآخرين وتُسلّط الضوء على المواهب المحلية.",
"Saudi talent message English": "We proudly celebrate Saudi Arabia’s growing film legacy.\nAs the founder, I created Scene to help grow Saudi cinema and to inspire and spotlight local talent. 🇸🇦",
"Loading director...": "Loading director...",
"Director not found.": "Director not found.",
"Director": "Director",
"directed films on Scene": "directed films on Scene",
"No directed films found.": "No directed films found.",
"No mutual friends have watched this director yet.": "No mutual friends have watched this director yet.",
"No watched films from this director yet.": "No watched films from this director yet.",
"Saudi filmmaker": "Saudi filmmaker",
"Scene celebrates local cinema talent": "Scene celebrates local cinema talent",

"No reviews found.": "No reviews found.",
"Pull to refresh or check again later.": "Pull to refresh or check again later.",

"Stay in the Scene": "Stay in the Scene",
"Get notified when friends reply, like, follow, or share movies with you.":
  "Get notified when friends reply, like, follow, or share movies with you.",
"Tap to enable": "Tap to enable",
"Enabling...": "Enabling...",
"Notifications enabled 🎬": "Notifications enabled 🎬",
"Scene will now send you updates when friends interact with you.":
  "Scene will now send you updates when friends interact with you.",
"Notifications not enabled": "Notifications not enabled",
"You can try again later from this banner.":
  "You can try again later from this banner.",
"Notifications failed": "Notifications failed",
"Something went wrong while enabling notifications.":
  "Something went wrong while enabling notifications.",

  },
  ar: {

    "Stay in the Scene": "ابقى داخل Scene",
"Get notified when friends reply, like, follow, or share movies with you.":
  "وصلك تنبيه لما أصدقاؤك يردون عليك، يعجبون بمراجعاتك، يتابعونك، أو يشاركونك أفلام.",
"Tap to enable": "اضغط للتفعيل",
"Enabling...": "جاري التفعيل...",
"Notifications enabled 🎬": "تم تفعيل التنبيهات 🎬",
"Scene will now send you updates when friends interact with you.":
  "Scene بيرسل لك تنبيهات لما أصدقاؤك يتفاعلون معك.",
"Notifications not enabled": "لم يتم تفعيل التنبيهات",
"You can try again later from this banner.":
  "تقدر تجرب مرة ثانية لاحقًا من هذا البنر.",
"Notifications failed": "فشل تفعيل التنبيهات",
"Something went wrong while enabling notifications.":
  "صار خطأ أثناء تفعيل التنبيهات.",

    "No reviews found.": "لا توجد مراجعات.",
"Pull to refresh or check again later.": "اسحب للتحديث أو تحقق مرة أخرى لاحقًا.",

    "Loading director...": "جارٍ تحميل المخرج...",
"Director not found.": "لم يتم العثور على المخرج.",
"Director": "مخرج",
"directed films on Scene": "فيلم من إخراجه على Scene",
"No directed films found.": "لم يتم العثور على أفلام من إخراجه.",
"No mutual friends have watched this director yet.": "لا يوجد أصدقاء مشتركون شاهدوا أعمال هذا المخرج بعد.",
"No watched films from this director yet.": "لا توجد أفلام تمت مشاهدتها لهذا المخرج بعد.",
"Saudi filmmaker": "صانع أفلام سعودي",
"Scene celebrates local cinema talent": "تحتفي Scene بالمواهب السينمائية المحلية",

    "Loading actor...": "جارٍ تحميل الممثل...",
"Actor not found.": "لم يتم العثور على الممثل.",
"Go Back": "رجوع",
"Unknown": "غير معروف",
"Untitled": "بدون عنوان",
"User": "مستخدم",

"Actor": "ممثل",
"Award data coming soon": "بيانات الجوائز قريبًا",
"films on Scene": "فيلم على Scene",

"Awards": "الجوائز",
"Biography": "السيرة الذاتية",
"No biography yet.": "لا توجد سيرة ذاتية بعد.",

"Career Progress": "تقدم المشاهدة",
"You": "أنت",
"watched": "مشاهدة",
"Friends": "الأصدقاء",
"friends": "أصدقاء",

"All Films": "كل الأفلام",
"No films found.": "لم يتم العثور على أفلام.",

"Friends Career %": "نسبة مشاهدة الأصدقاء",
"No mutual friends have watched this actor yet.": "لا يوجد أصدقاء مشتركون شاهدوا أعمال هذا الممثل بعد.",

"Your watched films": "الأفلام التي شاهدتها",
"of career by": "من مسيرة",
"No watched films from this actor yet.": "لا توجد أفلام تمت مشاهدتها لهذا الممثل بعد.",
"Logged": "تم التسجيل",

"Saudi talent message Arabic": "نحتفي ونفخر بإرث السعودية السينمائي المتنامي.\nكمؤسس للمنصة، أنشأت Scene على أمل أن نسهم في نمو السينما السعودية،\nوأن نلهم الآخرين وتُسلّط الضوء على المواهب المحلية.",
"Saudi talent message English": "We proudly celebrate Saudi Arabia’s growing film legacy.\nAs the founder, I created Scene to help grow Saudi cinema and to inspire and spotlight local talent. 🇸🇦",

"No cast available.": "لا توجد قائمة ممثلين متاحة.",
"Cinematography": "التصوير السينمائي",
"Unknown": "غير معروف",
"Full Cast": "طاقم التمثيل الكامل",
"Show less": "عرض أقل",
"Show more": "عرض المزيد",
    "Loading cinematographer...": "جارٍ تحميل المصور السينمائي...",
"Cinematographer not found.": "لم يتم العثور على المصور السينمائي.",
"Go Back": "رجوع",
"Unknown": "غير معروف",
"Untitled": "بدون عنوان",
"User": "مستخدم",

"Cinematographer": "مصور سينمائي",
"Camera Department": "قسم التصوير",
"Award data coming soon": "بيانات الجوائز قريبًا",
"cinematography credits on Scene": "أعمال تصوير سينمائي على Scene",

"Awards": "الجوائز",
"Biography": "السيرة الذاتية",
"No biography yet.": "لا توجد سيرة ذاتية بعد.",

"Career Progress": "تقدم المشاهدة",
"You": "أنت",
"watched": "مشاهدة",
"Friends": "الأصدقاء",
"friends": "أصدقاء",

"Cinematography Credits": "أعمال التصوير السينمائي",
"No cinematography credits found.": "لم يتم العثور على أعمال تصوير سينمائي.",

"Friends Career %": "نسبة مشاهدة الأصدقاء",
"No mutual friends have watched this cinematographer yet.": "لا يوجد أصدقاء مشتركون شاهدوا أعمال هذا المصور السينمائي بعد.",

"Your watched credits": "الأعمال التي شاهدتها",
"of credits by": "من أعمال",
"No watched cinematography credits yet.": "لا توجد أعمال تصوير سينمائي تمت مشاهدتها بعد.",
"Logged": "تم التسجيل",

    "Join Scene": "انضم إلى Scene",
"Create your account to log your films": "نشئ حسابك لتسجيل أفلامك",
"Upload Avatar": "ارفع صورة الحساب",
"Username": "اسم المستخدم",
"Email": "البريد الإلكتروني",
"Password": "كلمة المرور",
"Choose Language": "اختر اللغة",
"Selected": "المحدد",
"Sign Up": "إنشاء حساب",
"Already have an account?": "لديك حساب بالفعل؟",
"Log in": "تسجيل الدخول",

"Please upload an avatar.": "يرجى رفع صورة للحساب.",
"Invalid username format.": "صيغة اسم المستخدم غير صحيحة.",
"Username already taken.": "اسم المستخدم مستخدم بالفعل.",
"Invalid email.": "البريد الإلكتروني غير صحيح.",
"Email already in use.": "البريد الإلكتروني مستخدم بالفعل.",
"Password too short.": "كلمة المرور قصيرة جدًا.",
"Account created!": "تم انشاء حساب",
"Signup failed. Try again.": "فشل إنشاء الحساب. حاول مرة أخرى.",
"Error": "خطأ",
"English selected": "تم اختيار الإنجليزية",
"Arabic selected": "تم اختيار العربية",

    "Privacy Policy":"سياسة الخوصية",
    "Edit Profile": "تعديل الملف الشخصي",
    "Share": "مشاركة",
    "Settings": "الإعدادات",
    "Followers": "المتابِعون",
    "Following": "المتابَعون",
    "Films": "الأفلام",
    "Profile": "الملف الشخصي",
    "Reviews": "المراجعات",
    "Watchlist": "قائمة المشاهدة",
    "Lists": "القوائم",
    "Follow": "متابعة",
    "Following (btn)": "يتابع", 
    "Log Out": "تسجيل الخروج",
    "Delete Account": "حذف الحساب",
    "Change Language": "تغيير اللغة",
    "Remove Follower": "إزالة متابع",
    "🔗 Profile link copied!": "🔗 تم نسخ رابط الملف الشخصي",
    "Couldn’t copy link": "لم يتم نسخ الرابط",
    "Favorite Movies": "الأفلام المفضلة",
"No favorite movies yet.": "لا توجد أفلام مفضلة بعد",
"Recent Activities": "الأنشطة الأخيرة",
"No recent logs yet.": "لا توجد أنشطة حديثة بعد",
"More →": "المزيد →",
"Connections": "الروابط الشخصية",
"Hide": "إخفاء",
"Show": "إظهار",
"Most Recent": "الأحدث",
"Most Likes": "الأكثر إعجابًا",
"reply": "رد",
"replies": "الردود",
"Account": "الحساب",
"App Info": "معلوماتنا",
"Contact Us": "للتواصل",
"Built with ❤️ in Saudi Arabia": "بُني بحب في السعودية ❤️",
"All rights reserved.": "جميع الحقوق محفوظة.",

"Loading your Scenes...": "جارٍ تحميل مشاهدك...",
"Recently Added": "أضيفت مؤخرًا",
"Release Date": "تاريخ الإصدار",
"Rating": "التقييم",
"Runtime": "مدة العرض",
"All Genres": "كل الأنواع",
"Action": "أكشن",
"Comedy": "كوميديا",
"Drama": "دراما",
"Horror": "رعب",
"Romance": "رومانسية",
"Animation": "رسوم متحركة",
"Crime": "جريمة",
"Thriller": "إثارة",

"This movie has no valid TMDB ID.": "هذا الفيلم لا يحتوي على معرف TMDB صالح.",
"This watchlist is empty.": "قائمة المشاهدة فارغة.",

"My lists": "قوائمي",
"Saved": "المحفوظة",
"Popular": "الرائجة",
"Friends": "الأصدقاء",
"Add List": "إضافة قائمة",
"unknown": "مجهول",
"Family": "عائلي",

"Favorites": "المفضلة",
"Descending": "تنازلي",
"Ascending": "تصاعدي",
"You haven’t marked any favorite films yet.": "لم تحدد أي أفلام كمفضلة بعد.",
"No films found for this filter.": "لم يتم العثور على أفلام لهذا الفلتر.",
"Poster": "ملصق",
 
"No changes to save.": "لا توجد تغييرات للحفظ.",
"Profile updated!": "!تم تحديث الملف الشخصي",
"Failed to update profile.": "فشل تحديث الملف الشخصي.",
"Avatar uploaded!": "تم رفع الصورة الشخصية!",
"Avatar upload failed.": "فشل رفع الصورة الشخصية.",
"Back": "رجوع",
"Save": "حفظ",
"Backdrop": "الخلفية",
"Avatar": "الصورة الشخصية",
"Change Photo": "تغيير الصورة",
"Change backdrop": "تغيير الخلفية",
"Bio": "نبذة",
"Write a short bio (max 180 chars)": "اكتب نبذة قصيرة (بحد أقصى 180 حرفًا)",
"Favorite Films": "الأفلام المفضلة",
"No favorite movies yet.": "لا توجد أفلام مفضلة بعد.",
"Add Movie": "إضافة فيلم",
"Connections": "الروابط الشخصية",
"Add your social links (X, YouTube, etc.)": "أضف روابطك الاجتماعية (إكس، يوتيوب، إلخ)",
"Add / Edit Connections": "إضافة / تعديل الروابط",
"Enter your {{platform}} link or username": "أدخل رابط أو اسم مستخدم {{platform}}",
"Transfer Data from Letterboxd": "نقل البيانات من Letterboxd",
"Music": "موسيقي",

  "Import complete.": "اكتمل الاستيراد.",
  "Welcome to Scene!": " !نورتنا ❤️ حياك الله في سين",
  "Cleared last import.": "تم مسح آخر عملية استيراد.",
  "How to import": "كيفية الاستيراد",
  "Transfer Data from Letterboxd": "نقل البيانات من Letterboxd",
  "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).": "قم برفع ملفاتك المُصدّرة واحدًا تلو الآخر من مجلد بيانات Letterboxd (مثل watchlist.csv و ratings.csv).",
  "Uploading files...": "جاري رفع الملفات لا تغلق التطبيق...",
  "Upload All Files": "رفع جميع الملفات",
  "Continue to Profile": "المتابعة إلى الملف الشخصي",
  "Undo Last Import": "تراجع عن آخر استيراد",
  "How to Import from Letterboxd": " Letterboxd كيفية الاستيراد من" ,
  "Go to your Letterboxd account on the website (not the app).": "عبر الموقع وليس التطبيق (Letterboxd) اذهب إلى حسابك في ",
  "Go to Settings → Export your data.": " (Export Your Data) ثم ← (Settings) اذهب إلى  ",
  "Come back to Scene.": "عد إلى سين.",
  "Upload them here in the correct fields.": "قم برفعها هنا في الحقول الصحيحة.",
  "Click Save — we'll handle the rest! 🚀": "🚀 اضغط حفظ — والباقي علينا ",
  "Close": "إغلاق",
  "Back": "رجوع",
  "❌ Import failed for {{type}}": "❌ فشل الاستيراد لقسم {{type}}",

  "Add Movie": "إضافة فيلم",
  "Back": "رجوع",
  "Search movies...": "ابحث عن الأفلام...",
  "Loading...": "جارٍ التحميل...",
  "No results found.": "لم يتم العثور على نتائج.",
  "Already added": "مضاف بالفعل",
  "Added": "تمت الإضافة",

  "Followers": "المتابِعون",
  "Following": "المتابَعون",
  "User": "مستخدم",
  "Back": "رجوع",
  "Cancel": "رجوع",
  "cancel": "رجوع",
  "No users found.": "لا يوجد مستخدمون.",
  "Follow": "متابعة",
  "Unfollow": "إلغاء المتابعة",
  "{{name}}’s {{tab}}": "‏{{tab}} الخاصة بـ {{name}}",

  "Link copied with preview!": "تم نسخ الرابط مع المعاينة",
  "🎨 Change Backdrop": "🎨 تغيير الخلفية",
  "✏️ Edit Review/Log": "✏️ تعديل المراجعة",
  "🗑️ Delete Review/Log": "🗑️ حذف المراجعة",
  "📤 Share to Friends": "📤 مشاركة مع الأصدقاء",
  "💾 Save Photo": "💾 حفظ الصورة",
  "🔗 Copy Link": "🔗 نسخ الرابط",
  "Go to Movie": "اذهب إلى الفيلم",
  "Backdrop": "الخلفية",
  "Avatar": "الصورة الشخصية",
  "Just now": "الآن",
  "{{n}}m ago": "قبل {{n}} دقيقة",
  "{{n}}h ago": "قبل {{n}} ساعة",
  "{{n}}d ago": "قبل {{n}} يوم",
  "Rewatch count": "عدد مرات الإعادة",
  "Attached image": "صورة مرفقة",
  "GIF": "صورة متحركة GIF",
  "Like": "إعجاب",
  "Reply": "رد",
  "Back": "رجوع",

  "confirm_delete_log_title": "حذف السجل؟",
  "confirm_delete_log_message": "هل أنت متأكد أنك تريد حذف هذا السجل؟ لا يمكن التراجع عن هذا الإجراء.",
  "cancel": "إلغاء",
  "delete": "حذف",

  "watchlist.added": "تمت الإضافة إلى قائمة المشاهدة ✅",
  "watchlist.removed": "تمت الإزالة من قائمة المشاهدة ❌",
  "favorites.added": "تمت الإضافة إلى المفضلة ❤️",
  "favorites.removed": "تمت الإزالة من المفضلة ❌",

  "Delete this review?": "هل تريد حذف هذه المراجعة؟",
  "Review deleted!": "🗑️ تم حذف المراجعة ",
  "log_deleted": " 🗑️ تم حذف سجل المشاهدة ",
  "Failed to delete review.": "فشل حذف المراجعة.",
  "Failed to load review.": "فشل تحميل المراجعة.",
  "You must be logged in to like.": "يجب تسجيل الدخول لوضع إعجاب.",
  "Failed to like.": "فشل وضع الإعجاب.",
  "Failed to like reply.": "فشل وضع الإعجاب على الرد.",
  "Comments": "التعليقات",
  "No comments yet.": "لا توجد تعليقات بعد.",
  "Avatar": "الصورة الشخصية",
  "Image": "صورة",

  "More reviews": "مراجعات أخرى",
  "…read more": "…اقرأ المزيد",

  "No comments yet. Be the first to reply!": "لا توجد تعليقات بعد. كن أول من يرد!",
  "Options": "خيارات",
  "Delete": "حذف",
  "Reply sent": "تم إرسال الرد",
  "Failed to send reply": "فشل إرسال الرد",
  "Delete this reply?": "هل تريد حذف هذا الرد؟",
  "Reply deleted": "تم حذف الرد",
  "Failed to delete reply": "فشل حذف الرد",
  "Preview": "معاينة",
  "Remove attachment": "إزالة المرفق",
  "Add image": "إضافة صورة",
  "Add GIF": "إضافة صورة متحركة GIF",
  "Write a comment...": "اكتب تعليقًا...",
  "Send": "إرسال",

  "List title": "عنوان القائمة",
  "Description (optional)": "الوصف (اختياري)",
  "Upload a cover image (optional)": "ارفع صورة الخلفية (اختياري)",
  "Cover": "صورة الخلفية",
  "Remove": "إزالة",
  "Private": "قائمة خاصة",
  "Ranked": "بالترتيب",
  "Movies in this list:": "الأفلام في هذه القائمة:",
  "No movies added yet.": "لا توجد أفلام مضافة بعد.",
  "Add Movie": "إضافة فيلم",
  "List created!": "تم إنشاء القائمة!",
  "Failed to create list.": "فشل إنشاء القائمة.",
  "Upload failed.": "فشل الرفع.",
  "Cover uploaded!": "تم رفع صورة الخلفية!",

  "Failed to load list.": "فشل تحميل القائمة.",
  "List updated!": "تم تحديث القائمة!",
  "Failed to update list.": "فشل تحديث القائمة.",
  "Are you sure you want to delete this list?": "هل أنت متأكد أنك تريد حذف هذه القائمة؟",
  "List deleted.": "تم حذف القائمة.",
  "Upload failed.": "فشل الرفع.",



  "You must be logged in.": "يجب أن تسجّل الدخول.",
  "Something went wrong.": "حدث خطأ ما.",
  "List saved!": "تم حفظ القائمة!",
  "List unsaved!": "تم إلغاء حفظ القائمة!",
  "Are you sure you want to delete this list?": "هل أنت متأكد أنك تريد حذف هذه القائمة؟",
  "List deleted!": "تم حذف القائمة!",
  "Failed to delete list.": "فشل حذف القائمة.",
  "Loading...": "جارٍ التحميل...",
  "More options": "المزيد من الخيارات",
  "Edit List": "تعديل القائمة",
  "Share to Friends": "مشاركة مع الأصدقاء",
  "Delete List": "حذف القائمة",
  "Save List": "حفظ القائمة",
  "Ranked Movies": "الأفلام بالترتيب",
  "Movies": "الأفلام",
  "Untitled": "بدون عنوان",

  "Mystery": "غموض",
  "Adventure": "مغامرة",

  "Notifications": "الإشعارات",
  "You're all caught up. No notifications yet!": "كل شيء محدث. لا توجد إشعارات بعد!",
  "Failed to load notifications": "فشل في تحميل الإشعارات",
  "🔔 New notification": "🔔 إشعار جديد",
  "Something went wrong": "حدث خطأ ما",
  "just followed you": "قام بمتابعتك",
  "liked your review": "أعجب بمراجعتك",
  "liked your comment": "أعجب بتعليقك",
  "replied to your comment": "رد على تعليقك",
  "liked your list!": "!أعجب بالقائمة الخاصة بك",
  "suggested you to check out this list!": "!اقترح عليك الاطلاع على هذه القائمة",
  "suggested you to check out this film!": "!اقترح عليك مشاهدة هذا الفيلم",
  "suggested you to check out this review!": "!اقترح عليك قراءة هذه المراجعة",
  "shared a movie with you!": "!شارك معك فيلماً",
  "sent you something!": "!أرسل لك شيئاً",
  "View Movie": "عرض الفيلم",
  "View List": "عرض القائمة",
  "View Review": "عرض المراجعة",

  "Search": "بحث",
  "Recent Searches": "عمليات البحث الأخيرة",
  "Clear": "مسح",
  "No results found": "لا توجد نتائج",
  "Movies": "الأفلام",
  "Users": "المستخدمون",
  "Lists": "القوائم",
  "Actors": "الممثلون",
  "Directors": "المخرجون",
  "Trending Searches": "عمليات البحث الرائجة",
  "Search results": "نتائج البحث",
  "More →": "المزيد →",

  "Loading your Scenes...": "جاري تحميل مشاهدك...",
  "Welcome back, {name} 🎬": "🎬 {name} مرحبا بعودتك",
  "New Day. New Amazing Film. It’s a Scene Thing. 🎥": " يوم جديد، فلم رائع جديد، بس في سين !  🎥"  ,
  "Read more": "اقرأ المزيد",
  "Recent Activities": "الأنشطة الأخيرة",
  "No recent logs yet.": "لا توجد أنشطة حديثة بعد.",
  "Trending Movies": "الأفلام الرائجة",
  "More →": "المزيد →",
  "No trending movies right now.": "لا توجد أفلام رائجة حالياً.",

  "Trending Movies This Week 🔥": " 🔥 الأفلام الرائجة هذا الأسبوع",
  "No trending movies available.": "لا توجد أفلام رائجة متاحة.",

  "Ask Anything about Movies...": "اسأل أي شيء عن الأفلام...",
  "SceneBot is typing...": "سين بوت يكتب...",
  "Send": "إرسال",
  "Surprise me!": "فاجئني!",
  "Something went wrong": "حدث خطأ ما",

  "Loading...": "جاري التحميل...",
  "Profile link copied!": "تم نسخ رابط الملف الشخصي!",
  "Remove this follower?": "هل تريد إزالة هذا المتابع؟",
  "Removed follower!": "تمت إزالة المتابع!",

  "loading_movie": "جاري تحميل الفيلم...",
  "overview": "القصة",
  "director": "المخرج",
  "no_director_found": "لا يوجد مخرج",
  "starring": "بتمثيل",
  "watched_by_friends": "شاهدها أصدقاؤك",
  "no_friends_logged": "لا يوجد أصدقاء سجلوا هذا الفيلم بعد.",
  "more": "المزيد →",
  "popular_reviews": "المراجعات الشائعة",
  "no_reviews": "لا توجد مراجعات بعد.",
  "reply": "رد",
  "read_more": "اقرأ المزيد",
  "time.just_now": "الآن",
  "time.minutes_ago": "منذ {{min}} دقيقة",
  "time.hours_ago": "منذ {{hr}} ساعة",
  "time.days_ago": "منذ {{day}} يوم",
  "alt.backdrop": "خلفية",
  "no_trailer": "لا يوجد إعلان متاح",
  "scenebot_autoask": "ما رأيك في \"{{title}}\"؟", 

  "alt.poster": "الملصق",
  "minutes": "دقيقة",
  "log": "تسجيل المشاهدة",
  "trailer": "إعلان",
  "ask_scenebot": "اسأل سين بوت",



      "not_logged_in": "غير مسجل الدخول",
      "invalid_movie_id": "معرّف فيلم غير صالح",
      "watchlist_update_failed": "فشل في تحديث قائمة المشاهدة",
      "favorites_update_failed": "فشل في تحديث المفضلة",
      "delete_log_failed": "فشل في حذف تسجيل المشاهدة",
    

      "added": "تمت الإضافة إلى قائمة المشاهدة",
      "removed": "تمت الإزالة من قائمة المشاهدة",


      "added": "تمت الإضافة إلى المفضلة",
      "removed": "تمت الإزالة من المفضلة",
  

 

      "deleted_success": "تم حذف السجل بنجاح!",
  

  
          "change_poster": "تغيير الملصق",
          "remove_from_watchlist": "إزالة من قائمة المشاهدة",
          "add_to_watchlist": "إضافة إلى قائمة المشاهدة",
          "remove_from_favorites": "إزالة من المفضلة",
          "add_to_favorites": "إضافة إلى المفضلة",
          "add_to_list": "إضافة إلى قائمة",
          "share_to_friend": "مشاركة مع صديق",
          "delete_log": "حذف تسجيل المشاهدة",
  
      
      "back": "رجوع",
      "open_menu": "فتح القائمة",

      "Full Cast": "طاقم التمثيل كاملًا",
      "Similar Films": "أفلام مشابهة",
      "Where to Watch": "أماكن المشاهدة",

      "poster.choose_new": " اختر ملصقًا جديدًا",
      "poster.confirm": "✅ تأكيد",
      "poster.saving": "جاري الحفظ...",
      "poster.close": "إغلاق",
      "poster.approved_only": "يمكن استخدام الملصق المعتمد فقط لهذا الفيلم.",
      "poster.alt": "ملصق",

      "no_rating_yet": "لا يوجد تقييم بعد",
      "marked_as_favorite": "مضاف إلى المفضلة",
      "mark_as_favorite": "أضف إلى المفضلة",
      "mark_as_rewatch": "أضف كمشاهدة ثانية",
      "write_your_thoughts": "اكتب أفكارك...",
      "update": "تحديث",
      "log": "تسجيل",
      "log_updated": "✅ تم تحديث المشاهدة!",
      "log_submitted": "🎬 تم تسجيل المشاهدة!",
      "log_failed": "فشل في تسجيل المشاهدة.",

      "not_logged_in": "غير مسجل الدخول",
      "untitled_log": "مشاهدة بدون عنوان",
      "untitled_list": "قائمة بدون عنوان",
      "select_at_least_one": "اختر صديق واحد على الأقل.",
      "suggested_success": "✅ تم الإرسال إلى {{count}} صديق",
      "failed_to_send": "فشل في إرسال الاقتراحات.",
      "loading": "جاري التحميل...",
      "invalid_resource": "مورد غير صالح",
      "something_wrong": "حدث خطأ ما.",
      "go_back": "رجوع",
      "share_to_friends": "شارك مع الأصدقاء",
      "send": "إرسال",
      "no_mutual_followers": "لا يوجد لديك متابعين مشتركين بعد.",

      "lists.select_add": "اختر قائمة لإضافة هذا الفيلم",
      "lists.loading": "جاري تحميل قوائمك...",
      "lists.none_yet": "لم تقم بإنشاء أي قوائم بعد.",
      "lists.failed_load": "❌ فشل في تحميل القوائم",
      "lists.added_success": "✅ تمت الإضافة إلى القائمة!",
      "lists.added_fail": "❌ فشل في إضافة الفيلم.",
      "ask_anything": "اسأل أي شيء عن الأفلام...",

      "watched_by": "تمت المشاهدة بواسطة",
      "friends": "الأصدقاء",
      "all": "الكل",
      "no_friends_logged": "لم يقم أي صديق بتسجيل هذا الفيلم بعد.",
      "no_one_logged": "لم يقم أي شخص بتسجيل هذا الفيلم بعد.",

      "just_now": "الآن",
      "minutes_ago": "قبل {min} دقيقة",
      "hours_ago": "قبل {hr} ساعة",
      "days_ago": "قبل {day} يوم",

      "friends_reviews": "مراجعات الأصدقاء",
      "all_reviews": "كل المراجعات",

      "write_reply": "اكتب رداً...",
      "reply_sent": "تم إرسال الرد 🎉",
      "reply_failed": "فشل في إرسال الرد ❌",

      "loading": "جاري التحميل...",
      "check_imdb": "قد يكون لدى هذا الشخص جوائز – تحقق من IMDb لمزيد من المعلومات",
      "read_more": "اقرأ المزيد",
      "show_less": "إظهار أقل",
      "all_films": "جميع الأفلام",
      "all_directed_films": "جميع الأفلام التي أخرجها",

      "awards.imdb_fallback":   "🏆 IMDB لمزيد من التفاصيل تحقق من ",

      "Loading...": "جارٍ التحميل...",
      "I’ve rated": "لقد قمت بتقييم",
      "on": "على",
      "Saved! Check your device's Downloads folder.": "✅ تم الحفظ! تحقق من مجلد التنزيلات في جهازك.",

      "Change Backdrop": "تغيير الخلفية",
      "Search for a movie": "ابحث عن فيلم",
      "Loading backdrops...": "جارٍ تحميل الخلفيات...",
      "Done": "تم",

      "loading_actor": "جاري تحميل الممثل…",
      "loading_director": "جاري تحميل المخرج…",
  "Loading review…":"جارٍ تحميل المراجعة...",
        "select_a_list": "اختر قائمة",
  "no_lists_yet": "لا توجد لديك قوائم بعد.",
  "Backdrop updated successfully!":"✅ تم تحديث الخلفية!",



  "not_logged_in": "تحتاج لتسجيل الدخول أولاً",
  "invalid_movie_id": "معرّف الفيلم غير صالح",
  "watchlist_update_failed": "فشل تحديث قائمة المشاهدة",
  "favorites_update_failed": "فشل تحديث المفضلة",
  "delete_log_failed": "فشل حذف المراجعة",
  "failed_load_lists": "فشل تحميل قوائمك",
  "missing_movie": "بيانات الفيلم غير متوفرة",
  "failed_add_to_list": "فشل إضافة الفيلم إلى القائمة",


  "added": "تمت الإضافة إلى قائمة المشاهدة",
  "removed": "تمت الإزالة من قائمة المشاهدة",


  "added": "تمت الإضافة إلى المفضلة",
  "removed": "تمت الإزالة من المفضلة",


  "deleted_success": "تم حذف المراجعة بنجاح",


  "title": "هل أنت متأكد؟",


"added_to": "تمت الإضافة إلى",
"already_in_list": "هذا الفيلم موجود بالفعل في القائمة",
"select_a_list": "اختر قائمة",
"no_lists_yet": "ليس لديك أي قوائم حتى الآن.",
"like": "إعجاب",
"likes": "إعجابات",
"logout": "تسجيل الخروج",
"Films": "الأفلام",
"Loading...": "جاري التحميل...",


"Search For a movie": "ابحث عن فيلم",
    
  }
};



// tiny helper to replace {{placeholders}}
function interpolate(str, params) {
    if (!params) return str;
    return str.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, k) =>
      params[k] != null ? String(params[k]) : `{{${k}}}`
    );
  }
  
  export default function useTranslate() {
    const { language } = useLanguage();
  
    return (text, params) => {
      const table = dictionary[language] || {};
      const enTable = dictionary.en || {};
      // try current language, then fall back to EN, then raw
      const base =
        (table && table[text]) ||
        (enTable && enTable[text]) ||
        text;
      return interpolate(base, params);
    };
  }
