// 🎲 Fun prompts

export const funPrompts = {
    english: [
    "Suggest a movie where the villain was actually right",
    "What's a movie that completely messes with your head?",
    "Give me a film that has no happy ending, but it's still amazing",
    "Recommend an underrated animated movie",
    "Tell me a movie where the twist shocked you",
    "What’s a comforting movie to watch after a long day?",
    "List a film where the soundtrack makes it 10x better",
    "What's a hilarious movie I’ve probably never heard of?",
    "Recommend a movie that takes place in one location only",
    "Suggest a movie with a genius protagonist",
    "What’s the most visually stunning film ever made?",
    "Give me a movie with zero CGI that still amazes you",
    "What’s a film that starts slow but ends perfectly?",
    "Suggest a dark comedy that actually makes you think",
    "What movie feels like a fever dream?",
    "Which movie has the best use of silence?",
    "Name a film that made you rethink everything",
    "Movie with the best opening scene ever?",
    "Suggest a movie that feels like poetry",
    "What’s the scariest non-horror movie ever?",
    "Movie where a side character stole the show",
    "Best movie with a time loop?",
    "What’s a film with no antagonist?",
    "Best found-footage film?",
    "A movie that made you cry unexpectedly",
    "A movie where the ending completely changes the story",
    "Best ensemble cast in a movie?",
    "Suggest a movie with iconic narration",
    "Movie that feels like a dream",
    "A film that’s better the second time you watch it",
    "Best movie where the setting is basically a character",
    "Movie that nails the 'coming of age' theme",
    "Suggest a foreign film that’s unforgettable",
    "Movie where the villain is more relatable than the hero",
    "A film that plays in real time",
    "A film with an unforgettable voiceover",
    "Best movie with a single-word title?",
    "What’s a film that defined a generation?",
    "Movie with the most clever title?",
    "Suggest a film with the most unexpected genre mashup",
    "Movie that would be 10x better with a different ending",
    "Most quotable film of all time?",
    "A perfect revenge movie?",
    "A great film that happens in one night?",
    "Movie that represents pure chaos",
    "Film that feels like a rollercoaster start to finish",
    "Movie with the most satisfying twist?",
    "What’s a film with a totally unreliable narrator?",
    "Suggest a film that’s all vibes no plot",
    "A movie where silence is more powerful than dialogue",
    "A movie where the music tells the story",
    "Best movie where nothing happens — and it’s still great",
    "Movie that uses dreams in a brilliant way",
    "Movie that scared you without jump scares",
    "Movie with the most beautiful final shot",
    "Film where every scene could be a wallpaper",
    "Suggest a film with a brilliant flashback structure",
    "What’s a great courtroom drama?",
    "Best use of nonlinear storytelling?",
    "Movie that explores grief in a unique way",
    "Movie that feels like autumn 🍂",
    "Movie that feels like summer ☀️",
    "Best movie set on a train?",
    "Movie where the title has a double meaning",
    "Film that proves less is more",
    "Suggest a movie with unreliable timelines",
    "A movie you have to pause and rewind constantly",
    "Best use of voice acting in animation?",
    "Movie that makes you question reality",
    "Film that uses color like a character",
    "A film that made you sit in silence afterward",
    "Best use of reverse chronology?",
    "Movie with best long takes (no cuts)?",
    "Movie where the city is basically a main character",
    "Best movie with a countdown or ticking clock",
    "Most iconic final line in a movie?",
    "A movie with a color-based theme?",
    "Movie where food plays a key emotional role",
    "Suggest a movie where no one is truly good or bad",
    "Movie where the title only makes sense at the end",
    "Movie that works like a puzzle",
    "Best movie where reality and fiction blur",
    "Movie where animation is used in live-action scenes",
    "Movie that uses dance in a powerful way",
    "Movie where the score is better than the film",
    "Movie with brilliant opening credits",
    "Movie that feels like a video game",
    "A movie that would work as a stage play",
    "Movie that lives in your head rent-free",
    "Best movie that takes place during one season only",
    "A movie where the weather is symbolic",
    "Best movie that ends with a question",
    "Best movie about making a movie",
    "Most suspenseful moment in any film?",
    "Movie that captures loneliness perfectly",
    "Suggest a movie where art is central to the story",
    "Movie where the main character has zero dialogue",
    "Best movie that uses real-time aging (Boyhood-style)",
    "Movie with the best mid-movie twist",
    "A movie that’s better at home than in theaters",
    "Movie where you rooted for the wrong person",
    "Movie that feels like an anxiety attack",
    "Movie where mirrors play a huge role",
    "Film with the most layered symbolism",
    "Best slow-burn thriller?",
    "Most creative use of editing?",
    "Film with an ending you’ll never forget",
    "Movie that made you proud of your culture",
    "Movie that hits different after a breakup",
    "Movie that feels like a memory",
    "Best minimalist film?",
    "Best black-and-white movie released in the 21st century?",
    "Movie that makes you want to travel",
    "Movie that feels like falling in love",
    "Suggest a movie with a brilliant anti-hero",
    "Movie where the fashion deserves its own Oscar",
    "A movie where animals are the smartest characters",
    "Movie that would work great as a video game",
    "Movie with the best 1v1 showdown",
    "A movie where dreams and reality mix seamlessly",
    "Movie where the ending scene replays in your head",
    "A movie where the trailer spoiled everything",
    "A movie with no background score at all",
    "Best use of split-screen in a movie",
    "Movie that makes silence sound loud",
    "Best movie set inside one room",
    "Movie that’s 90% dialogue but still gripping",
    "Movie where the twist made the whole movie better",
    "Movie with characters you instantly relate to",
    "Movie with scenes that feel improvised",
    "Movie with the best fictional technology",
    "Movie where a single moment changes everything",
    "Best animated movie without a word of dialogue",
    "A movie that reinvents its own genre",
    "Movie that could only be made by one director",
    "A movie you immediately rewatched after finishing",
    "Movie that somehow gets better with every watch",
    "Movie where the ending broke you",
    "Movie where the villain actually wins",
    "Movie that turns comedy into tragedy",
    "Suggest a horror movie with no monsters",
    "Movie where the twist is hidden in plain sight",
    "Movie with the most underrated lead performance",
    "Movie that starts funny but ends terrifying",
    "Movie with the best use of practical effects",
    "Movie with no main character — just vibes",
    "Movie with the weirdest title that actually works",
    "Movie that takes place entirely in real time",
    "Movie where every second matters",
    "Movie where everyone dies, and it's still satisfying",
    "Best movie with unreliable memory as a plot device",
    "Movie that breaks the fourth wall in a clever way",
    "Movie that makes you feel nostalgic for a place you've never been",
    "Movie where the title becomes haunting by the end",
    "Movie with the most satisfying revenge arc",
    "A movie you didn’t understand at all — but loved",
    "Movie that feels like a modern myth",
    "Movie where the weather changes the tone completely",
    "A movie that aged better than anyone expected",
    "Movie that could easily be a novel",
    "Movie with the most emotional goodbye scene",
    "Movie that shows the beauty of silence",
    "Movie that makes you believe in cinema again",
    "Movie that starts happy and ends existential",
    "Movie where a lie drives the entire plot",
    "Movie where the audience knows more than the characters",
    "Movie that made you text someone immediately after",
    "A movie you regret not watching in theaters",
    "Best film that’s under 90 minutes",
    "Suggest a movie where music is a main character",
    "Movie where the twist completely redefines the story",
    "Movie that made you laugh and cry at the same time",
    "A movie where the villain was right all along",
],
arabic: [

    "اقترح فيلمًا يكون فيه الشرير على حق فعلاً",
    "ما هو فيلم يعبث بعقلك تمامًا؟",
    "أعطني فيلمًا ليس له نهاية سعيدة ولكنه لا يزال رائعًا",
    "رشح لي فيلم رسوم متحركة غير مشهور",
    "أخبرني عن فيلم كانت نهايته صادمة",
    "ما هو فيلم مريح للمشاهدة بعد يوم طويل؟",
    "اذكر فيلمًا يجعل الموسيقى التصويرية القصة أفضل بعشر مرات",
    "ما هو فيلم مضحك ربما لم أسمع به من قبل؟",
    "رشح فيلمًا تدور أحداثه في مكان واحد فقط",
    "اقترح فيلمًا يحتوي على بطل عبقري",
    "ما هو أكثر فيلم مذهل بصريًا تم إنتاجه؟",
    "أعطني فيلمًا بدون مؤثرات CGI ولكنه ما زال مدهشًا",
    "ما هو الفيلم الذي يبدأ ببطء لكن نهايته مثالية؟",
    "اقترح كوميديا سوداء تجعلك تفكر فعلًا",
    "ما هو الفيلم الذي يشبه الحلم المحموم؟",
    "أي فيلم استخدم الصمت بطريقة رائعة؟",
    "اذكر فيلمًا جعلك تعيد التفكير في كل شيء",
    "فيلم يحتوي على أفضل مشهد افتتاحي على الإطلاق؟",
    "اقترح فيلمًا يبدو وكأنه قصيدة",
    "ما هو أكثر فيلم مرعب من دون أن يكون رعبًا؟",
    "فيلم سرق فيه أحد الشخصيات الجانبية الأضواء",
    "أفضل فيلم يحتوي على حلقة زمنية؟",
    "ما هو الفيلم الذي لا يحتوي على شرير؟",
    "أفضل فيلم مصور بطريقة اللقطات المفقودة؟",
    "فيلم جعلك تبكي دون أن تتوقع ذلك",
    "فيلم نهايته غيرت كل القصة بالكامل",
    "أفضل طاقم تمثيل جماعي في فيلم؟",
    "اقترح فيلمًا يتميز بالسرد الصوتي الأيقوني",
    "فيلم يجعلك تشعر وكأنك في حلم",
    "فيلم يصبح أفضل عند مشاهدته للمرة الثانية",
    "أفضل فيلم تكون فيه البيئة وكأنها شخصية بحد ذاتها",
        "فيلم يتقن موضوع النضوج والتحول",
        "اقترح فيلمًا أجنبيًا لا يُنسى",
        "فيلم يكون فيه الشرير أكثر قابلية للتعاطف من البطل",
        "فيلم تدور أحداثه بالكامل في الوقت الحقيقي",
        "فيلم يحتوي على سرد صوتي لا يُنسى",
        "أفضل فيلم بعنوان كلمة واحدة؟",
        "ما هو الفيلم الذي عرّف جيلًا كاملًا؟",
        "فيلم يحمل عنوانًا عبقريًا ومبتكرًا",
        "اقترح فيلمًا يمزج بين أنواع غير متوقعة",
        "فيلم سيكون أفضل بعشر مرات بنهاية مختلفة",
        "أكثر فيلم يمكن اقتباسه على الإطلاق؟",
        "فيلم انتقامي مثالي؟",
        "فيلم رائع تدور أحداثه في ليلة واحدة فقط",
        "فيلم يمثل الفوضى الخالصة",
        "فيلم يشبه قطار الملاهي من البداية للنهاية",
        "فيلم يحتوي على أكثر نهاية مرضية",
        "فيلم يحتوي على راوي غير موثوق تمامًا؟",
        "اقترح فيلمًا كله أجواء بدون حبكة",
        "فيلم يكون فيه الصمت أقوى من الحوار",
        "فيلم تحكي فيه الموسيقى القصة",
        "أفضل فيلم لا يحدث فيه شيء — ومع ذلك رائع",
        "فيلم يستخدم الأحلام بطريقة عبقرية",
        "فيلم أخافك دون قفزات رعب",
        "فيلم يحتوي على أجمل لقطة ختامية",
        "فيلم يمكن أن تكون كل لقطة فيه خلفية شاشة",
        "اقترح فيلمًا يستخدم الفلاش باك بطريقة ذكية",
        "ما هو أفضل فيلم دراما في قاعة المحكمة؟",
        "أفضل استخدام للسرد غير الخطي؟",
        "فيلم يستكشف الحزن بطريقة فريدة",
        "فيلم يشعر وكأنه فصل الخريف 🍂",
        "فيلم يشعر وكأنه فصل الصيف ☀️",
        "أفضل فيلم تدور أحداثه في قطار؟",
        "فيلم يحمل عنوانًا بمعنيين مختلفين",
        "فيلم يثبت أن البساطة قوة",
        "اقترح فيلمًا بأزمنة غير موثوقة",
        "فيلم تحتاج لإيقافه وإرجاعه باستمرار",
        "أفضل أداء صوتي في فيلم رسوم متحركة؟",
        "فيلم يجعلك تشكك في الواقع",
        "فيلم يستخدم الألوان كشخصية بحد ذاتها",
        "فيلم يجعلك تجلس صامتًا بعد نهايته",
        "أفضل استخدام للترتيب الزمني العكسي؟",
        "فيلم يحتوي على أفضل لقطات طويلة بدون تقطيع؟",
        "فيلم تكون فيه المدينة شخصية رئيسية",
        "أفضل فيلم يحتوي على عد تنازلي أو ساعة تدق",
        "أكثر جملة ختامية أيقونية في فيلم؟",
        "فيلم يتمحور حول اللون؟",
        "فيلم تلعب فيه الأطعمة دورًا عاطفيًا أساسيًا",
        "اقترح فيلمًا لا يوجد فيه خير أو شر واضح",
        "فيلم لا تفهم عنوانه إلا بنهايته",
        "فيلم يعمل مثل أحجية أو لغز",
        "أفضل فيلم يطمس الحدود بين الواقع والخيال",
        "فيلم يستخدم الرسوم المتحركة في مشاهد حقيقية",
        "فيلم يستخدم الرقص بطريقة قوية",
        "فيلم تكون فيه الموسيقى أفضل من الفيلم نفسه",
        "فيلم يحتوي على مقدمة افتتاحية عبقرية",
        "فيلم يبدو وكأنه لعبة فيديو",
        "فيلم سيكون رائعًا كمسرحية",
        "فيلم يعيش في رأسك دون إيجار",
        "أفضل فيلم تدور أحداثه في فصل واحد فقط",
        "فيلم يكون فيه الطقس رمزًا عاطفيًا",
        "أفضل فيلم ينتهي بسؤال مفتوح",
        "أفضل فيلم عن صناعة فيلم",
        "أكثر لحظة مشوقة في أي فيلم؟",
        "فيلم يلتقط الشعور بالوحدة بدقة",
        "اقترح فيلمًا تكون فيه الفنون محور القصة",
        "فيلم لا يتكلم فيه البطل أبدًا",
        "أفضل فيلم يستخدم تقدم العمر الواقعي",
        "فيلم يحتوي على أفضل تطور مفاجئ في منتصفه",
        "فيلم تشاهده في المنزل ويكون أفضل من السينما",
        "فيلم كنت تشجع فيه الشخص الخطأ",
        "فيلم يشبه نوبة قلق",
        "فيلم تلعب فيه المرايا دورًا كبيرًا",
        "فيلم يحتوي على رمزية عميقة ومتعددة الطبقات",
        "أفضل إثارة بطيئة التصاعد؟",
        "أكثر استخدام إبداعي للمونتاج؟",
        "فيلم بنهاية لا تُنسى أبدًا",
        "فيلم جعلك فخورًا بثقافتك",
        "فيلم يكون له تأثير مختلف بعد الانفصال",
        "فيلم يشعر وكأنه ذكرى",
        "أفضل فيلم بسيط جدًا (مينيمالي)",
        "أفضل فيلم أبيض وأسود في القرن 21؟",
        "فيلم يجعلك ترغب في السفر",
        "فيلم يشعر وكأنك تقع في الحب",
        "اقترح فيلمًا يحتوي على بطل مضاد عبقري",
        "فيلم تستحق فيه الأزياء جائزة أوسكار",
        "فيلم تكون فيه الحيوانات أذكى من البشر",
        "فيلم سيكون رائعًا كلعبة فيديو",
        "فيلم يحتوي على أفضل مواجهة فردية",
        "فيلم تختلط فيه الأحلام بالواقع بسلاسة",
        "فيلم تعيد مشهد النهاية فيه مرارًا",
        "فيلم أفسد التريلر كل مفاجآته",
        "فيلم بدون موسيقى خلفية على الإطلاق",
        "أفضل استخدام لتقسيم الشاشة في فيلم",
        "فيلم يجعل الصمت يبدو صاخبًا",
        "أفضل فيلم تدور أحداثه في غرفة واحدة",
        "فيلم يعتمد بنسبة 90% على الحوار لكنه مشوق",
        "فيلم جعلت نهايته الفيلم بأكمله أفضل",
        "فيلم تحتوي شخصياته على صلة مباشرة بك",
        "فيلم يبدو أن مشاهده مرتجلة",
        "فيلم يحتوي على أفضل تكنولوجيا خيالية",
        "فيلم يغير كل شيء في لحظة واحدة",
        "أفضل فيلم رسوم متحركة بدون أي حوار",
        "فيلم يعيد تعريف نوعه بالكامل",
        "فيلم لا يمكن أن يصنعه إلا مخرج واحد",
        "فيلم أعدت مشاهدته فور انتهائه",
        "فيلم يصبح أفضل كلما شاهدته أكثر",
        "فيلم نهايته حطمتك",
        "فيلم ينتصر فيه الشرير فعليًا",
        "فيلم يحول الكوميديا إلى مأساة",
        "اقترح فيلم رعب بدون وحوش",
        "فيلم تكون فيه الحبكة ظاهرة لكن لا تلاحظها",
        "فيلم يحتوي على أداء رئيسي مظلوم جدًا",
        "فيلم يبدأ مضحكًا وينتهي مرعبًا",
        "فيلم يستخدم المؤثرات العملية بشكل مذهل",
        "فيلم بدون بطل رئيسي — فقط أجواء",
        "فيلم يحمل عنوانًا غريبًا لكنه ينجح",
        "فيلم تدور أحداثه بالكامل في الوقت الحقيقي",
        "فيلم كل ثانية فيه لها أهمية",
        "فيلم يموت فيه الجميع — ومع ذلك مرضي",
        "أفضل فيلم يستخدم فقدان الذاكرة كحبكة",
        "فيلم يكسر الجدار الرابع بطريقة ذكية",
        "فيلم يجعلك تشتاق لمكان لم تزره أبدًا",
        "فيلم يصبح عنوانه مرعبًا في النهاية",
        "فيلم يحتوي على أروع قوس انتقامي",
        "فيلم لم تفهمه إطلاقًا — لكن أحببته",
        "فيلم يشعر وكأنه أسطورة حديثة",
        "فيلم يتغير فيه الطقس فيغير كل الإحساس",
        "فيلم أصبح أفضل مع مرور الوقت",
        "فيلم يمكن تحويله بسهولة إلى رواية",
        "فيلم يحتوي على أكثر مشهد وداع مؤثر",
        "فيلم يظهر جمال الصمت",
        "فيلم يعيد إيمانك بالسينما",
        "فيلم يبدأ بسعادة وينتهي بوجودية",
        "فيلم تدفع فيه كذبة واحدة القصة كلها",
        "فيلم يعرف فيه الجمهور أكثر من الشخصيات",
        "فيلم يجعلك تراسل أحدهم فورًا بعد انتهائه",
        "فيلم تندم أنك لم تشاهده في السينما",
        "أفضل فيلم مدته أقل من 90 دقيقة",
        "اقترح فيلمًا تكون فيه الموسيقى شخصية رئيسية",
        "فيلم يغيره الالتواء تمامًا",
        "فيلم يجعلك تضحك وتبكي في نفس الوقت",
        "فيلم الشرير فيه كان على حق طوال الوقت",
          
]
};
