// src/utils/useTranslate.js
import { useLanguage } from "../context/LanguageContext";

const dictionary = {
  en: {
    "Edit Profile": "Edit Profile",
    "Share": "Share",
    "Settings": "Settings",
    "Followers": "Followers",
    "Following": "Following",
    "Films": "Films",
    "Profile": "Profile",
    "Reviews": "Reviews",
    "Watchlist": "Watchlist",
    "Lists": "Lists",
    "Follow": "Follow",
    "Following (btn)": "Following", 
    "Log Out": "Log Out",
    "Delete Account": "Delete Account",
    "Change Language": "Change Language",
    "Remove Follower": "Remove Follower",
    "🔗 Profile link copied!": "🔗 Profile link copied!",
    "Couldn’t copy link": "Couldn’t copy link",
    "Favorite Movies": "Favorite Movies",
"No favorite movies yet.": "No favorite movies yet.",
"Recent Activities": "Recent Activities",
"No recent logs yet.": "No recent logs yet.",
"More →": "More →",
"Connections": "Connections",
"Hide": "Hide",
"Show": "Show",
"Most Recent": "Most Recent",
    "Most Likes": "Most Likes",
    "reply": "reply",
    "replies": "replies",
    "Account": "Account",
    "App Info": "App Info",
    "Contact Us": "Contact Us",
    "Built with ❤️ in Saudi Arabia": "Built with ❤️ in Saudi Arabia",
    "All rights reserved.": "All rights reserved.",

    "Loading your Scenes...": "Loading your Scenes...",
    "Recently Added": "Recently Added",
    "Release Date": "Release Date",
    "Rating": "Rating",
    "Runtime": "Runtime",
    "All Genres": "All Genres",
    "Action": "Action",
    "Comedy": "Comedy",
    "Drama": "Drama",
    "Horror": "Horror",
    "Romance": "Romance",
    "Animation": "Animation",
    "Crime": "Crime",
    "Thriller": "Thriller",
    "This movie has no valid TMDB ID.": "This movie has no valid TMDB ID.",
    "This watchlist is empty.": "This watchlist is empty.",

    "My lists": "My lists",
    "Saved": "Saved",
    "Popular": "Popular",
    "Friends": "Friends",
    "Add List": "Add List",
    "unknown": "unknown",

    "Favorites": "Favorites",
    "Descending": "Descending",
    "Ascending": "Ascending",
    "You haven’t marked any favorite films yet.": "You haven’t marked any favorite films yet.",
    "No films found for this filter.": "No films found for this filter.",
    "Poster": "Poster",

    "No changes to save.": "No changes to save.",
    "Profile updated!": "Profile updated!",
    "Failed to update profile.": "Failed to update profile.",
    "Avatar uploaded!": "Avatar uploaded!",
    "Avatar upload failed.": "Avatar upload failed.",
    "Back": "Back",
    "Save": "Save",
    "Backdrop": "Backdrop",
    "Avatar": "Avatar",
    "Change Photo": "Change Photo",
    "Change backdrop": "Change backdrop",
    "Bio": "Bio",
    "Write a short bio (max 180 chars)": "Write a short bio (max 180 chars)",
    "Favorite Films": "Favorite Films",
    "No favorite movies yet.": "No favorite movies yet.",
    "Add Movie": "Add Movie",
    "Connections": "Connections",
    "Add your social links (X, YouTube, etc.)": "Add your social links (X, YouTube, etc.)",
    "Add / Edit Connections": "Add / Edit Connections",
    "Enter your {{platform}} link or username": "Enter your {{platform}} link or username",
    "Transfer Data from Letterboxd": "Transfer Data from Letterboxd",

    "Import complete.": "Import complete.",
    "Welcome to Scene!": "Welcome to Scene!",
    "Cleared last import.": "Cleared last import.",
    "How to import": "How to import",
    "Transfer Data from Letterboxd": "Transfer Data from Letterboxd",
    "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).": "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).",
    "Uploading files...": "Uploading files...",
    "Upload All Files": "Upload All Files",
    "Continue to Profile": "Continue to Profile",
    "Undo Last Import": "Undo Last Import",
    "How to Import from Letterboxd": "How to Import from Letterboxd",
    "Go to your Letterboxd account on the website (not the app).": "Go to your Letterboxd account on the website (not the app).",
    "Go to Settings → Export your data.": "Go to Settings → Export your data.",
    "Come back to Scene.": "Come back to Scene.",
    "Upload them here in the correct fields.": "Upload them here in the correct fields.",
    "Click Save — we'll handle the rest! 🚀": "Click Save — we'll handle the rest! 🚀",
    "Close": "Close",
    "Back": "Back",
    "❌ Import failed for {{type}}": "❌ Import failed for {{type}}",

    "Add Movie": "Add Movie",
    "Back": "Back",
    "Search movies...": "Search movies...",
    "Loading...": "Loading...",
    "No results found.": "No results found.",
    "Already added": "Already added",
    "Added": "Added",

    "Followers": "Followers",
    "Following": "Following",
    "User": "User",
    "Back": "Back",
    "No users found.": "No users found.",
    "Follow": "Follow",
    "Unfollow": "Unfollow",
    "{{name}}’s {{tab}}": "{{name}}’s {{tab}}",

    "Link copied with preview!": "Link copied with preview!",
    "🎨 Change Backdrop": "🎨 Change Backdrop",
    "✏️ Edit Review/Log": "✏️ Edit Review/Log",
    "🗑️ Delete Review/Log": "🗑️ Delete Review/Log",
    "📤 Share to Friends": "📤 Share to Friends",
    "💾 Save Photo": "💾 Save Photo",
    "🔗 Copy Link": "🔗 Copy Link",
    "Go to Movie": "Go to Movie",
    "Backdrop": "Backdrop",
    "Avatar": "Avatar",
    "Just now": "Just now",
    "{{n}}m ago": "{{n}}m ago",
    "{{n}}h ago": "{{n}}h ago",
    "{{n}}d ago": "{{n}}d ago",
    "Rewatch count": "Rewatch count",
    "Attached image": "Attached image",
    "GIF": "GIF",
    "Like": "Like",
    "Reply": "Reply",
    "Back": "Back",

    "Delete this review?": "Delete this review?",
    "Review deleted!": "Review deleted!",
    "Failed to delete review.": "Failed to delete review.",
    "Failed to load review.": "Failed to load review.",
    "You must be logged in to like.": "You must be logged in to like.",
    "Failed to like.": "Failed to like.",
    "Failed to like reply.": "Failed to like reply.",
    "Comments": "Comments",
    "No comments yet.": "No comments yet.",
    "Avatar": "Avatar",
    "Image": "Image",

    "More reviews": "More reviews",
    "…read more": "…read more",

    "No comments yet. Be the first to reply!": "No comments yet. Be the first to reply!",
    "Options": "Options",
    "Delete": "Delete",
    "Reply sent": "Reply sent",
    "Failed to send reply": "Failed to send reply",
    "Delete this reply?": "Delete this reply?",
    "Reply deleted": "Reply deleted",
    "Failed to delete reply": "Failed to delete reply",
    "Preview": "Preview",
    "Remove attachment": "Remove attachment",
    "Add image": "Add image",
    "Add GIF": "Add GIF",
    "Write a comment...": "Write a comment...",
    "Send": "Send",


    "List title": "List title",
    "Description (optional)": "Description (optional)",
    "Upload a cover image (optional)": "Upload a cover image (optional)",
    "Cover": "Cover",
    "Remove": "Remove",
    "Private": "Private",
    "Ranked": "Ranked",
    "Movies in this list:": "Movies in this list:",
    "No movies added yet.": "No movies added yet.",
    "Add Movie": "Add Movie",
    "List created!": "List created!",
    "Failed to create list.": "Failed to create list.",
    "Upload failed.": "Upload failed.",
    "Cover uploaded!": "Cover uploaded!",

    "Failed to load list.": "Failed to load list.",
    "List updated!": "List updated!",
    "Failed to update list.": "Failed to update list.",
    "Are you sure you want to delete this list?": "Are you sure you want to delete this list?",
    "List deleted.": "List deleted.",

    "You must be logged in.": "You must be logged in.",
    "Something went wrong.": "Something went wrong.",
    "List saved!": "List saved!",
    "List unsaved!": "List unsaved!",
    "Are you sure you want to delete this list?": "Are you sure you want to delete this list?",
    "List deleted!": "List deleted!",
    "Failed to delete list.": "Failed to delete list.",
    "Loading...": "Loading...",
    "More options": "More options",
    "Edit List": "Edit List",
    "Share to Friends": "Share to Friends",
    "Delete List": "Delete List",
    "Save List": "Save List",
    "Ranked Movies": "Ranked Movies",
    "Movies": "Movies",
    "Untitled": "Untitled",

    "Notifications": "Notifications",
    "You're all caught up. No notifications yet!": "You're all caught up. No notifications yet!",
    "Failed to load notifications": "Failed to load notifications",
    "🔔 New notification": "🔔 New notification",
    "Something went wrong": "Something went wrong",
    "just followed you": "just followed you",
    "liked your review": "liked your review",
    "liked your comment": "liked your comment",
    "replied to your comment": "replied to your comment",
    "liked your list!": "liked your list!",
    "suggested you to check out this list!": "suggested you to check out this list!",
    "suggested you to check out this film!": "suggested you to check out this film!",
    "suggested you to check out this review!": "suggested you to check out this review!",
    "shared a movie with you!": "shared a movie with you!",
    "sent you something!": "sent you something!",
    "View Movie": "View Movie",
    "View List": "View List",
    "View Review": "View Review",

    "Search": "Search",
    "Recent Searches": "Recent Searches",
    "Clear": "Clear",
    "No results found": "No results found",
    "Movies": "Movies",
    "Users": "Users",
    "Lists": "Lists",
    "Actors": "Actors",
    "Directors": "Directors",
    "Trending Searches": "Trending Searches",
    "Search results": "Search results",
    "More →": "More →",

    "Loading your Scenes...": "Loading your Scenes...",
    "Welcome back, {name} 🎬": "Welcome back, {name} 🎬",
    "Profile": "Profile",
    "New Day. New Amazing Film. It’s a Scene Thing. 🎥": "New Day. New Amazing Film. It’s a Scene Thing. 🎥",
    "Recent Activities": "Recent Activities",
    "No recent logs yet.": "No recent logs yet.",
    "Trending Movies": "Trending Movies",
    "More →": "More →",
    "No trending movies right now.": "No trending movies right now.",

    "Trending Movies This Week 🔥": "Trending Movies This Week 🔥",
    "No trending movies available.": "No trending movies available.",

    "Ask Anything about Movies...": "Ask Anything about Movies...",
    "SceneBot is typing...": "SceneBot is typing...",
    "Send": "Send",
    "Surprise me!": "Surprise me!",
    "Something went wrong": "Something went wrong",

    "Loading...": "Loading...",
    "Profile link copied!": "Profile link copied!",
    "Remove this follower?": "Remove this follower?",
    "Removed follower!": "Removed follower!",
    "Failed to remove follower.": "Failed to remove follower.",

  
  },
  ar: {
    "Edit Profile": "تعديل الملف الشخصي",
    "Share": "مشاركة",
    "Settings": "الإعدادات",
    "Followers": "المتابِعون",
    "Following": "المتابَعون",
    "Films": "الأفلام",
    "Profile": "الملف الشخصي",
    "Reviews": "المراجعات",
    "Watchlist": "قائمة المشاهدة",
    "Lists": "القوائم",
    "Follow": "متابعة",
    "Following (btn)": "يتابع", 
    "Log Out": "تسجيل الخروج",
    "Delete Account": "حذف الحساب",
    "Change Language": "تغيير اللغة",
    "Remove Follower": "إزالة متابع",
    "🔗 Profile link copied!": "🔗 تم نسخ رابط الملف الشخصي",
    "Couldn’t copy link": "لم يتم نسخ الرابط",
    "Favorite Movies": "الأفلام المفضلة",
"No favorite movies yet.": "لا توجد أفلام مفضلة بعد",
"Recent Activities": "الأنشطة الأخيرة",
"No recent logs yet.": "لا توجد أنشطة حديثة بعد",
"More →": "المزيد →",
"Connections": "الروابط الشخصية",
"Hide": "إخفاء",
"Show": "إظهار",
"Most Recent": "الأحدث",
"Most Likes": "الأكثر إعجابًا",
"reply": "رد",
"replies": "الردود",
"Account": "الحساب",
"App Info": "معلوماتنا",
"Contact Us": "للتواصل",
"Built with ❤️ in Saudi Arabia": "بُني بحب في السعودية ❤️",
"All rights reserved.": "جميع الحقوق محفوظة.",

"Loading your Scenes...": "جارٍ تحميل مشاهدك...",
"Recently Added": "أضيفت مؤخرًا",
"Release Date": "تاريخ الإصدار",
"Rating": "التقييم",
"Runtime": "مدة العرض",
"All Genres": "كل الأنواع",
"Action": "أكشن",
"Comedy": "كوميديا",
"Drama": "دراما",
"Horror": "رعب",
"Romance": "رومانسية",
"Animation": "رسوم متحركة",
"Crime": "جريمة",
"Thriller": "إثارة",
"This movie has no valid TMDB ID.": "هذا الفيلم لا يحتوي على معرف TMDB صالح.",
"This watchlist is empty.": "قائمة المشاهدة فارغة.",

"My lists": "قوائمي",
"Saved": "المحفوظة",
"Popular": "الرائجة",
"Friends": "الأصدقاء",
"Add List": "إضافة قائمة",
"unknown": "مجهول",

"Favorites": "المفضلة",
"Descending": "تنازلي",
"Ascending": "تصاعدي",
"You haven’t marked any favorite films yet.": "لم تحدد أي أفلام كمفضلة بعد.",
"No films found for this filter.": "لم يتم العثور على أفلام لهذا الفلتر.",
"Poster": "ملصق",

"No changes to save.": "لا توجد تغييرات للحفظ.",
"Profile updated!": "!تم تحديث الملف الشخصي",
"Failed to update profile.": "فشل تحديث الملف الشخصي.",
"Avatar uploaded!": "تم رفع الصورة الشخصية!",
"Avatar upload failed.": "فشل رفع الصورة الشخصية.",
"Back": "رجوع",
"Save": "حفظ",
"Backdrop": "الخلفية",
"Avatar": "الصورة الشخصية",
"Change Photo": "تغيير الصورة",
"Change backdrop": "تغيير الخلفية",
"Bio": "نبذة",
"Write a short bio (max 180 chars)": "اكتب نبذة قصيرة (بحد أقصى 180 حرفًا)",
"Favorite Films": "الأفلام المفضلة",
"No favorite movies yet.": "لا توجد أفلام مفضلة بعد.",
"Add Movie": "إضافة فيلم",
"Connections": "الروابط الشخصية",
"Add your social links (X, YouTube, etc.)": "أضف روابطك الاجتماعية (إكس، يوتيوب، إلخ)",
"Add / Edit Connections": "إضافة / تعديل الروابط",
"Enter your {{platform}} link or username": "أدخل رابط أو اسم مستخدم {{platform}}",
"Transfer Data from Letterboxd": "نقل البيانات من Letterboxd",

"Import complete.": "اكتمل الاستيراد.",
  "Welcome to Scene!": " !نورتنا ❤️ حياك الله في سين",
  "Cleared last import.": "تم مسح آخر عملية استيراد.",
  "How to import": "كيفية الاستيراد",
  "Transfer Data from Letterboxd": "نقل البيانات من Letterboxd",
  "Upload your exported files one by one from the Letterboxd data folder (watchlist.csv, ratings.csv, etc.).": "قم برفع ملفاتك المُصدّرة واحدًا تلو الآخر من مجلد بيانات Letterboxd (مثل watchlist.csv و ratings.csv).",
  "Uploading files...": "جاري رفع الملفات...",
  "Upload All Files": "رفع جميع الملفات",
  "Continue to Profile": "المتابعة إلى الملف الشخصي",
  "Undo Last Import": "تراجع عن آخر استيراد",
  "How to Import from Letterboxd": " Letterboxd كيفية الاستيراد من" ,
  "Go to your Letterboxd account on the website (not the app).": "عبر الموقع وليس التطبيق (Letterboxd) اذهب إلى حسابك في ",
  "Go to Settings → Export your data.": " (Export Your Data) ثم ← (Settings) اذهب إلى  ",
  "Come back to Scene.": "عد إلى سين.",
  "Upload them here in the correct fields.": "قم برفعها هنا في الحقول الصحيحة.",
  "Click Save — we'll handle the rest! 🚀": "🚀 اضغط حفظ — والباقي علينا ",
  "Close": "إغلاق",
  "Back": "رجوع",
  "❌ Import failed for {{type}}": "❌ فشل الاستيراد لقسم {{type}}",

  "Add Movie": "إضافة فيلم",
  "Back": "رجوع",
  "Search movies...": "ابحث عن الأفلام...",
  "Loading...": "جارٍ التحميل...",
  "No results found.": "لم يتم العثور على نتائج.",
  "Already added": "مضاف بالفعل",
  "Added": "تمت الإضافة",

  "Followers": "المتابِعون",
  "Following": "المتابَعون",
  "User": "مستخدم",
  "Back": "رجوع",
  "No users found.": "لا يوجد مستخدمون.",
  "Follow": "متابعة",
  "Unfollow": "إلغاء المتابعة",
  "{{name}}’s {{tab}}": "‏{{tab}} الخاصة بـ {{name}}",

  "Link copied with preview!": "تم نسخ الرابط مع المعاينة",
  "🎨 Change Backdrop": "🎨 تغيير الخلفية",
  "✏️ Edit Review/Log": "✏️ تعديل المراجعة",
  "🗑️ Delete Review/Log": "🗑️ حذف المراجعة",
  "📤 Share to Friends": "📤 مشاركة مع الأصدقاء",
  "💾 Save Photo": "💾 حفظ الصورة",
  "🔗 Copy Link": "🔗 نسخ الرابط",
  "Go to Movie": "اذهب إلى الفيلم",
  "Backdrop": "الخلفية",
  "Avatar": "الصورة الشخصية",
  "Just now": "الآن",
  "{{n}}m ago": "قبل {{n}} دقيقة",
  "{{n}}h ago": "قبل {{n}} ساعة",
  "{{n}}d ago": "قبل {{n}} يوم",
  "Rewatch count": "عدد مرات الإعادة",
  "Attached image": "صورة مرفقة",
  "GIF": "صورة متحركة GIF",
  "Like": "إعجاب",
  "Reply": "رد",
  "Back": "رجوع",

  "Delete this review?": "هل تريد حذف هذه المراجعة؟",
  "Review deleted!": "تم حذف المراجعة!",
  "Failed to delete review.": "فشل حذف المراجعة.",
  "Failed to load review.": "فشل تحميل المراجعة.",
  "You must be logged in to like.": "يجب تسجيل الدخول لوضع إعجاب.",
  "Failed to like.": "فشل وضع الإعجاب.",
  "Failed to like reply.": "فشل وضع الإعجاب على الرد.",
  "Comments": "التعليقات",
  "No comments yet.": "لا توجد تعليقات بعد.",
  "Avatar": "الصورة الشخصية",
  "Image": "صورة",

  "More reviews": "مراجعات أخرى",
  "…read more": "…اقرأ المزيد",

  "No comments yet. Be the first to reply!": "لا توجد تعليقات بعد. كن أول من يرد!",
  "Options": "خيارات",
  "Delete": "حذف",
  "Reply sent": "تم إرسال الرد",
  "Failed to send reply": "فشل إرسال الرد",
  "Delete this reply?": "هل تريد حذف هذا الرد؟",
  "Reply deleted": "تم حذف الرد",
  "Failed to delete reply": "فشل حذف الرد",
  "Preview": "معاينة",
  "Remove attachment": "إزالة المرفق",
  "Add image": "إضافة صورة",
  "Add GIF": "إضافة صورة متحركة GIF",
  "Write a comment...": "اكتب تعليقًا...",
  "Send": "إرسال",

  "List title": "عنوان القائمة",
  "Description (optional)": "الوصف (اختياري)",
  "Upload a cover image (optional)": "ارفع صورة الخلفية (اختياري)",
  "Cover": "صورة الخلفية",
  "Remove": "إزالة",
  "Private": "قائمة خاصة",
  "Ranked": "بالترتيب",
  "Movies in this list:": "الأفلام في هذه القائمة:",
  "No movies added yet.": "لا توجد أفلام مضافة بعد.",
  "Add Movie": "إضافة فيلم",
  "List created!": "تم إنشاء القائمة!",
  "Failed to create list.": "فشل إنشاء القائمة.",
  "Upload failed.": "فشل الرفع.",
  "Cover uploaded!": "تم رفع صورة الخلفية!",

  "Failed to load list.": "فشل تحميل القائمة.",
  "List updated!": "تم تحديث القائمة!",
  "Failed to update list.": "فشل تحديث القائمة.",
  "Are you sure you want to delete this list?": "هل أنت متأكد أنك تريد حذف هذه القائمة؟",
  "List deleted.": "تم حذف القائمة.",
  "Upload failed.": "فشل الرفع.",



  "You must be logged in.": "يجب أن تسجّل الدخول.",
  "Something went wrong.": "حدث خطأ ما.",
  "List saved!": "تم حفظ القائمة!",
  "List unsaved!": "تم إلغاء حفظ القائمة!",
  "Are you sure you want to delete this list?": "هل أنت متأكد أنك تريد حذف هذه القائمة؟",
  "List deleted!": "تم حذف القائمة!",
  "Failed to delete list.": "فشل حذف القائمة.",
  "Loading...": "جارٍ التحميل...",
  "More options": "المزيد من الخيارات",
  "Edit List": "تعديل القائمة",
  "Share to Friends": "مشاركة مع الأصدقاء",
  "Delete List": "حذف القائمة",
  "Save List": "حفظ القائمة",
  "Ranked Movies": "الأفلام بالترتيب",
  "Movies": "الأفلام",
  "Untitled": "بدون عنوان",

  "Notifications": "الإشعارات",
  "You're all caught up. No notifications yet!": "كل شيء محدث. لا توجد إشعارات بعد!",
  "Failed to load notifications": "فشل في تحميل الإشعارات",
  "🔔 New notification": "🔔 إشعار جديد",
  "Something went wrong": "حدث خطأ ما",
  "just followed you": "قام بمتابعتك",
  "liked your review": "أعجب بمراجعتك",
  "liked your comment": "أعجب بتعليقك",
  "replied to your comment": "رد على تعليقك",
  "liked your list!": "!أعجب بالقائمة الخاصة بك",
  "suggested you to check out this list!": "!اقترح عليك الاطلاع على هذه القائمة",
  "suggested you to check out this film!": "!اقترح عليك مشاهدة هذا الفيلم",
  "suggested you to check out this review!": "!اقترح عليك قراءة هذه المراجعة",
  "shared a movie with you!": "!شارك معك فيلماً",
  "sent you something!": "!أرسل لك شيئاً",
  "View Movie": "عرض الفيلم",
  "View List": "عرض القائمة",
  "View Review": "عرض المراجعة",

  "Search": "بحث",
  "Recent Searches": "عمليات البحث الأخيرة",
  "Clear": "مسح",
  "No results found": "لا توجد نتائج",
  "Movies": "الأفلام",
  "Users": "المستخدمون",
  "Lists": "القوائم",
  "Actors": "الممثلون",
  "Directors": "المخرجون",
  "Trending Searches": "عمليات البحث الرائجة",
  "Search results": "نتائج البحث",
  "More →": "المزيد →",

  "Loading your Scenes...": "جاري تحميل مشاهدك...",
  "Welcome back, {name} 🎬": "🎬 {name} مرحبا بعودتك",
  "New Day. New Amazing Film. It’s a Scene Thing. 🎥": "🎥 !يوم جديد، فلم رائع جديد، بس في سين "  ,
  "Read more": "اقرأ المزيد",
  "Recent Activities": "الأنشطة الأخيرة",
  "No recent logs yet.": "لا توجد أنشطة حديثة بعد.",
  "Trending Movies": "الأفلام الرائجة",
  "More →": "المزيد →",
  "No trending movies right now.": "لا توجد أفلام رائجة حالياً.",

  "Trending Movies This Week 🔥": " 🔥 الأفلام الرائجة هذا الأسبوع",
  "No trending movies available.": "لا توجد أفلام رائجة متاحة.",

  "Ask Anything about Movies...": "اسأل أي شيء عن الأفلام...",
  "SceneBot is typing...": "سين بوت يكتب...",
  "Send": "إرسال",
  "Surprise me!": "فاجئني!",
  "Something went wrong": "حدث خطأ ما",

  "Loading...": "جاري التحميل...",
  "Profile link copied!": "تم نسخ رابط الملف الشخصي!",
  "Remove this follower?": "هل تريد إزالة هذا المتابع؟",
  "Removed follower!": "تمت إزالة المتابع!",
  },
};

// tiny helper to replace {{placeholders}}
function interpolate(str, params) {
    if (!params) return str;
    return str.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, k) =>
      params[k] != null ? String(params[k]) : `{{${k}}}`
    );
  }
  
  export default function useTranslate() {
    const { language } = useLanguage();
  
    return (text, params) => {
      const table = dictionary[language] || {};
      const enTable = dictionary.en || {};
      // try current language, then fall back to EN, then raw
      const base =
        (table && table[text]) ||
        (enTable && enTable[text]) ||
        text;
      return interpolate(base, params);
    };
  }
